New Article : kronecker product
oumpy/hp_management pull request #375
Opened 2021-02-09 01:58 UTC by takyamamoto

2021-02-11 12:11 UTC, atamaokac requested changes
Points mentioned in Slack.

2021-02-21 01:03 UTC, atamaokac requested changes
I proposed minor corrections in the branch `article/kronecker_product_atamaokac`.

2021-02-21 12:08 UTC, takyamamoto commented
Thank @atamaokac for your correction.

2021-02-22 08:50 UTC, atamaokac approved these changes

2021-02-22 08:51 UTC, merged